/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Database.datatable;
import Database.dbcnx;
import Database.parameter;
import java.awt.Frame;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author hp
 */
public class facturation extends javax.swing.JFrame {

    /**
     * Creates new form facturation
     */
    ResultSet rs;
    dbcnx db;
    
     
    public facturation() {
        db=new dbcnx(new parameter().HOST_DB,new parameter().USERNAME_DB,new parameter().PASSWORD_DB,new parameter().IPHOST,new parameter().PORT);
        initComponents();
      time();
      date();
      setResizable(false);
      setExtendedState(JFrame.MAXIMIZED_BOTH);
      SetIcon();
      table();
      tablee1();
      tableee();
    }
    
     public void table(){
            String t[]=
            {"Reference","Nom_P","prix","Quantite","Description","Total"};
            rs=db.SelectSome(t,"tablefacture");
            tablee.setModel(new datatable(rs) {});
            
        }
     
     
        public void tablee1(){
            String t[]=
            {"cin","nom","prenom","tel","email","adress","sex"};
            rs=db.SelectSome(t,"client");
            Table1.setModel(new datatable(rs) {});
        }
         public void tableee(){
            String t[]=
            {"reference","nom_produit","prix","description"};
            rs=db.SelectSome(t,"produit");
            Table4.setModel(new datatable(rs) {});
        }

    
     public void actualiser(){
        gg.setText("");
       }
   
     public void actu(){
        v.setText("");
        f.setText("");
        PP.setText("");
//        qu.setText("");
        g.setText("");
        tu.setText("");
        to.setText("");
        c.setText("");
        n.setText("");
        p.setText("");
        t.setText("");
        e.setText("");
        a.setText("");
        kl.setText("");
        re.setText("");
     }
     
    public void time(){
        DateTimeFormatter times =DateTimeFormatter.ofPattern("hh : mm a");
        LocalDateTime now =LocalDateTime.now();
        time.setText(times.format(now));
    } 
    public void date(){
        DateTimeFormatter times =DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDateTime now =LocalDateTime.now();
        date.setText(times.format(now));
    }
   
     public void total() {
        double aa = Double.parseDouble(PP.getText());
        double bb = Double.parseDouble(qu.getText());
        double cc = aa * bb;        
        tu.setText(String.valueOf(cc));
}
     
     
     
   public void tabb(){
         gg.setText(gg.getText()+"-----------------------------------------------------------------------------------------------------------------------------------------------------\n");
      
        gg.setText(gg.getText()+"Reference"+"\t"+"Nom_P"+"\t"+"Prix"+"\t"+"Quantite"+ "\t"+"Description"+"\t"+"Total"+    "\n");
        
       for(int i = 0;i<tablee.getRowCount();i++){
            String Reference=tablee.getValueAt(i, 0).toString();
             gg.setText(gg.getText()+"-----------------------------------------------------------------------------------------------------------------------------------------------------\n");
            String Nom_P=tablee.getValueAt(i, 1).toString();
            String Prix=tablee.getValueAt(i, 2).toString();
            String Quantite=tablee.getValueAt(i, 3).toString();
            String Description=tablee.getValueAt(i, 4).toString();
            String Total=tablee.getValueAt(i, 5).toString();
            gg.setText(gg.getText()+Reference+"\t"+Nom_P+"\t"+Prix+"\t"+Quantite+"\t"+Description+"\t"+Total+    " DH \n");   
          
        }
          gg.setText(gg.getText()+"-----------------------------------------------------------------------------------------------------------------------------------------------------\n");
   }         

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        c = new javax.swing.JTextField();
        n = new javax.swing.JTextField();
        t = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        e = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        a = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        v = new javax.swing.JTextField();
        f = new javax.swing.JTextField();
        PP = new javax.swing.JTextField();
        qu = new javax.swing.JTextField();
        g = new javax.swing.JTextField();
        cal = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        gg = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        p = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        vv = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablee = new javax.swing.JTable();
        to = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        tu = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        aa = new javax.swing.JLabel();
        kl = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        Table4 = new javax.swing.JTable();
        re = new javax.swing.JTextField();
        re1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Details Client :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 127, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("cin");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 250, 30, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nom");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tel");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 250, 30, -1));
        getContentPane().add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 250, 110, -1));
        getContentPane().add(n, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 250, 102, -1));
        getContentPane().add(t, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 250, 104, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(728, 250, 56, -1));
        getContentPane().add(e, new org.netbeans.lib.awtextra.AbsoluteConstraints(798, 250, 117, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Adresse");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(938, 250, 70, -1));
        getContentPane().add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(1018, 250, 118, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Details Produit :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 127, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Ref");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 330, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nom_P");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 330, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Prix");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 330, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Description");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 330, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Quantite");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(858, 330, -1, -1));
        getContentPane().add(v, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 330, 102, -1));
        getContentPane().add(f, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 330, 130, -1));
        getContentPane().add(PP, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 330, 82, -1));

        qu.setText("1");
        qu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quActionPerformed(evt);
            }
        });
        qu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                quKeyTyped(evt);
            }
        });
        getContentPane().add(qu, new org.netbeans.lib.awtextra.AbsoluteConstraints(938, 330, 70, -1));
        getContentPane().add(g, new org.netbeans.lib.awtextra.AbsoluteConstraints(698, 330, 126, -1));

        cal.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        cal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/foto/diskette.png"))); // NOI18N
        cal.setText("Ajouter facture");
        cal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calActionPerformed(evt);
            }
        });
        getContentPane().add(cal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 489, 200, -1));

        gg.setColumns(20);
        gg.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        gg.setRows(5);
        gg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        gg.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ggAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        gg.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ggComponentShown(evt);
            }
        });
        jScrollPane2.setViewportView(gg);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 509, 304));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Prenom");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 250, -1, -1));
        getContentPane().add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 250, 102, -1));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("DH");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 330, -1, -1));

        jButton2.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/foto/copy.png"))); // NOI18N
        jButton2.setText("Imprimer facture");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 579, 200, -1));

        jButton4.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/foto/close.png"))); // NOI18N
        jButton4.setText("Fermer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 625, 200, -1));

        jButton5.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/foto/refresh.png"))); // NOI18N
        jButton5.setText("Actualiser");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 535, 200, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Andalus", 1, 25)); // NOI18N
        jLabel2.setText("Facture");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 31, -1, -1));

        vv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/foto/accounting.png"))); // NOI18N
        jPanel1.add(vv, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 16, -1, -1));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 16, 79, -1));
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(1127, 16, 139, -1));
        jPanel1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(1127, 51, 147, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 90));

        jButton6.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/foto/budget (1).png"))); // NOI18N
        jButton6.setText("Calcul");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 443, 200, -1));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("DH");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 330, -1, 26));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Prix T Poduit");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1018, 330, -1, -1));

        tablee.setBackground(new java.awt.Color(0, 51, 51));
        tablee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablee);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 720, 30, 20));

        to.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toActionPerformed(evt);
            }
        });
        getContentPane().add(to, new org.netbeans.lib.awtextra.AbsoluteConstraints(1104, 380, 118, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Total HT");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 380, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("DH");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1232, 390, -1, 10));

        tu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuActionPerformed(evt);
            }
        });
        getContentPane().add(tu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1128, 330, 96, -1));

        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Table1);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 470, 90));

        aa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aa.setForeground(new java.awt.Color(255, 255, 255));
        aa.setText("Entrer la Cin");
        getContentPane().add(aa, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 100, -1));

        kl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                klActionPerformed(evt);
            }
        });
        kl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                klKeyReleased(evt);
            }
        });
        getContentPane().add(kl, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 140, -1));

        Table4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table4MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(Table4);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 430, 200));

        re.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reActionPerformed(evt);
            }
        });
        re.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                reKeyReleased(evt);
            }
        });
        getContentPane().add(re, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 140, -1));

        re1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        re1.setForeground(new java.awt.Color(255, 255, 255));
        re1.setText("Entrer la Reference");
        getContentPane().add(re1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/foto/pexels-share-textures-11285435.jpg"))); // NOI18N
        jLabel17.setText("jLabel17");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 80, -1, -1));

        setSize(new java.awt.Dimension(1300, 794));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void calActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calActionPerformed
      time();
      date();
      
       if (c.getText().equals("")  || p.getText().equals("") || n.getText().equals("") || t.getText().equals("") || e.getText().equals("")  || a.getText().equals("") || v.getText().equals("") ||f.getText().equals("") ||PP.getText().equals("") ||g.getText().equals("") ||tu.getText().equals("") ||qu.getText().equals("") ||to.getText().equals("")  ) 
       {
 JOptionPane.showMessageDialog(this, "Selectionner les Details");
       }else{
        gg.append("\n\tInstitu Technique des sciences Nouvelles  \n\t****************************************"
                + " \n\n Devloppmentt informatique\n Maroc,Tetouan,Mohamed kharraz 513 \n Telephone : (+212)622190567 \n"+
                "\n------------------------------------------------------------------------------------------------------------------\n\n"+
                 
                "\t\t\tDate :\t"+date.getText()+"\n"+
                "\t\t\tTime :\t"+time.getText()+"\n\n"+
            
        "Cin :\t"+c.getText()+"\n\n"+
        "Nom :\t"+n.getText()+"\n\n"+  
        "Prenom :\t"+p.getText()+"\n\n"+      
        "Telefon :\t"+t.getText()+"\n\n"+  
        "Email :\t"+e.getText()+"\n\n"+
        "Address :\t"+a.getText()+"\n\n"  
                        
                );
           tabb();
        
             gg.append("\t"+"\n"+
       
        "\t***********************************************************\n"+             
         "\t\tTotal HT :\t"+to.getText()+" DH \n"+     
         "\t***********************************************************\n"+ 
          "\n\tSignature : \n\n\t cache : \n"
                     
             );
             System.out.println(db.DeleteData("tablefacture"));
           table();
           actu();
       }
    }//GEN-LAST:event_calActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        if (gg.getText().equals("") ){
            
        }
        else
        try {
            gg.print();
        } catch (PrinterException ex) {
            Logger.getLogger(facturation.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
          System.out.println(db.DeleteData("tablefacture"));
        ClientProduit m=new ClientProduit();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
           actualiser();
           System.out.println(db.DeleteData("tablefacture"));
           table(); 
           actu();
           tablee1();
           tableee();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         total();
                if(v.getText().equals("") || f.getText().equals("") || PP.getText().equals("") || qu.getText().equals("") || g.getText().equals("") || tu.getText().equals("") ){
            JOptionPane.showMessageDialog(this,"champ vide");
        }else{
            String[] colon=
            {"Reference","Nom_P","prix","Quantite","Description","Total"};
            
            String[] inf={v.getText(),f.getText(),PP.getText(),qu.getText(),g.getText(),tu.getText()};
            System.out.println(db.Insertdata("tablefacture",colon,inf));

           table();          
        }
               
          int numrow =tablee.getRowCount();
        
        double tot=0;
        
        for(int i=0; i< numrow; i++){
            double val = Double.valueOf(tablee.getValueAt(i, 5).toString());
            tot +=val;
            
        }
        to.setText(Double.toString(tot));
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void quActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
         gg.setEditable(false);
         c.setEditable(false);
          n.setEditable(false);
          p.setEditable(false);
          t.setEditable(false);
          e.setEditable(false);
          a.setEditable(false);
          v.setEditable(false);
          f.setEditable(false);
          PP.setEditable(false);
          g.setEditable(false);
          tu.setEditable(false);
          to.setEditable(false);
    }//GEN-LAST:event_formComponentShown

    private void quKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quKeyTyped
        // TODO add your handling code here:
           char car =evt.getKeyChar();
        if((car<'0' || car >'9') && qu.getText().contains(".") &&(car!=(char)KeyEvent.VK_BACK_SPACE)){
        evt.consume();
//        JOptionPane.showInputDialog(null,"seuls les chiffres sont autorisés","valider les numéros",JOptionPane.INFORMATION_MESSAGE);
        
       
    }else if((car<'0' || car >'9') &&(car!='.') 
            &&(car!=(char)KeyEvent.VK_BACK_SPACE)){
        evt.consume();
//        JOptionPane.showMessageDialog(null,"seuls les chiffres sont autorisés","valider les numéros",JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_quKeyTyped

    private void ggComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ggComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_ggComponentShown

    private void ggAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ggAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_ggAncestorAdded

    private void tableeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableeMouseClicked
        // TODO add your handling code here:
//        v.setText(String.valueOf(tablee.getValueAt(tablee.getSelectedRow(),0)));
//        f.setText(String.valueOf(tablee.getValueAt(tablee.getSelectedRow(),1)));
//        PP.setText(String.valueOf(tablee.getValueAt(tablee.getSelectedRow(),2)));
//        qu.setText(String.valueOf(tablee.getValueAt(tablee.getSelectedRow(),3)));
//        g.setText(String.valueOf(tablee.getValueAt(tablee.getSelectedRow(),4)));
//        tu.setText(String.valueOf(tablee.getValueAt(tablee.getSelectedRow(),5)));
    }//GEN-LAST:event_tableeMouseClicked

    private void Table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table1MouseClicked
        // TODO add your handling code here:
        kl.setText(String.valueOf(Table1.getValueAt(Table1.getSelectedRow(),0)));
        c.setText(String.valueOf(Table1.getValueAt(Table1.getSelectedRow(),0)));
        n.setText(String.valueOf(Table1.getValueAt(Table1.getSelectedRow(),1)));
        p.setText(String.valueOf(Table1.getValueAt(Table1.getSelectedRow(),2)));
        t.setText(String.valueOf(Table1.getValueAt(Table1.getSelectedRow(),3)));
        e.setText(String.valueOf(Table1.getValueAt(Table1.getSelectedRow(),4)));
        a.setText(String.valueOf(Table1.getValueAt(Table1.getSelectedRow(),5)));
      
    }//GEN-LAST:event_Table1MouseClicked

    private void klActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_klActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_klActionPerformed

    private void klKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_klKeyReleased
        // TODO add your handling code here:
         if(aa.getText().equals("Entrer la Cin")) {
                rs = db.SelectALL("client", "cin LIKE '%" + kl.getText() + "%' ");
                Table1.setModel(new datatable(rs){});
            }
    }//GEN-LAST:event_klKeyReleased

    private void toActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toActionPerformed

    private void Table4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table4MouseClicked
        // TODO add your handling code here:
         re.setText(String.valueOf(Table4.getValueAt(Table4.getSelectedRow(),0)));
        v.setText(String.valueOf(Table4.getValueAt(Table4.getSelectedRow(),0)));
        f.setText(String.valueOf(Table4.getValueAt(Table4.getSelectedRow(),1)));
        PP.setText(String.valueOf(Table4.getValueAt(Table4.getSelectedRow(),2)));
        g.setText(String.valueOf(Table4.getValueAt(Table4.getSelectedRow(),3)));
        tu.setText(String.valueOf(Table4.getValueAt(Table4.getSelectedRow(),2)));
    }//GEN-LAST:event_Table4MouseClicked

    private void reKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reKeyReleased
        // TODO add your handling code here:
           if(re1.getText().equals("Entrer la Reference")) {
                rs = db.SelectALL("produit", "reference LIKE '%" + re.getText() + "%' ");
                Table4.setModel(new datatable(rs){});
            }
    }//GEN-LAST:event_reKeyReleased

    private void tuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tuActionPerformed

    private void reActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reActionPerformed
   
/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(facturation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(facturation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(facturation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(facturation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new facturation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PP;
    private javax.swing.JTable Table1;
    private javax.swing.JTable Table4;
    private javax.swing.JTextField a;
    private javax.swing.JLabel aa;
    private javax.swing.JTextField c;
    private javax.swing.JButton cal;
    private javax.swing.JLabel date;
    private javax.swing.JTextField e;
    private javax.swing.JTextField f;
    private javax.swing.JTextField g;
    private javax.swing.JTextArea gg;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField kl;
    private javax.swing.JTextField n;
    private javax.swing.JTextField p;
    private javax.swing.JTextField qu;
    private javax.swing.JTextField re;
    private javax.swing.JLabel re1;
    private javax.swing.JTextField t;
    private javax.swing.JTable tablee;
    private javax.swing.JLabel time;
    private javax.swing.JTextField to;
    private javax.swing.JTextField tu;
    private javax.swing.JTextField v;
    private javax.swing.JLabel vv;
    // End of variables declaration//GEN-END:variables
 private void SetIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("rating.png")));
    }
}
