/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Database.datatable;
import Database.dbcnx;
import Database.parameter;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

public class mdfclient extends javax.swing.JFrame {

    /**
     * Creates new form mdfclient
     */
    ResultSet rs;
    dbcnx db;
    
    String idc;
    String nomc;
    String pren;
    String te ;
    String ema;
    String ad;
    String s;
    
    public mdfclient( String idcin , String nomc , String pren , String te , String ema , String ad , String s  ) {
        this.idc=idcin;
        this.nomc=nomc;
        this.pren=pren;
        this.te=te;
        this.ema=ema;
        this.ad=ad;
        this.s=s;
        
        
        db=new dbcnx(new parameter().HOST_DB,new parameter().USERNAME_DB,new parameter().PASSWORD_DB,new parameter().IPHOST,new parameter().PORT);
        initComponents();
        cin.setText(idc);   
        nom.setText(nomc); 
        prenom.setText(pren);
        teel.setText(te);   
        emmai.setText(ema); 
        add.setText(ad);
        sss.setSelectedItem(s);
        
        
    }
      public mdfclient() {
        db=new dbcnx(new parameter().HOST_DB,new parameter().USERNAME_DB,new parameter().PASSWORD_DB,new parameter().IPHOST,new parameter().PORT);
        initComponents();
        setResizable(false);
        SetIcon();
    }
        
      
    
     public void actualiser(){
        cin.setText("");
        nom.setText("");
        prenom.setText("");
        emmai.setText("");
        teel.setText("");
        add.setText(""); 
        sss.setSelectedIndex(1);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cin = new javax.swing.JTextField();
        nom = new javax.swing.JTextField();
        teel = new javax.swing.JTextField();
        emmai = new javax.swing.JTextField();
        add = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        tt = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        prenom = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        di = new javax.swing.JTextField();
        sss = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/foto/icons8-client-management-80.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 29, -1, -1));

        jLabel2.setFont(new java.awt.Font("Algerian", 1, 22)); // NOI18N
        jLabel2.setText("Modifier Client");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 60, 209, -1));

        jLabel4.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        jLabel4.setText("Cin");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 190, 42, -1));

        jLabel5.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        jLabel5.setText("Nom");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        jLabel6.setText("Tel");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 310, -1, -1));

        jLabel7.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        jLabel7.setText("Email");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 350, -1, -1));

        jLabel8.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 458, -1, -1));

        jLabel9.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        jLabel9.setText("sex");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 435, -1, -1));

        jLabel10.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 449, -1, -1));

        jLabel11.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        jLabel11.setText("Adress");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 390, -1, -1));

        cin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cinKeyTyped(evt);
            }
        });
        getContentPane().add(cin, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 190, 206, -1));

        nom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nomKeyTyped(evt);
            }
        });
        getContentPane().add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 230, 206, -1));

        teel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                teelKeyTyped(evt);
            }
        });
        getContentPane().add(teel, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 310, 150, -1));

        emmai.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                emmaiFocusLost(evt);
            }
        });
        getContentPane().add(emmai, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 350, 206, -1));
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 390, 206, -1));

        jButton1.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/foto/refresh.png"))); // NOI18N
        jButton1.setText("Actualiser");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 501, -1, -1));

        tt.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        tt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/foto/order.png"))); // NOI18N
        tt.setText("Modifier");
        tt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttActionPerformed(evt);
            }
        });
        getContentPane().add(tt, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 501, 185, -1));

        jButton3.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/foto/close.png"))); // NOI18N
        jButton3.setText("Fermer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 554, 160, -1));

        jLabel12.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        jLabel12.setText("Prenom");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 270, -1, -1));

        prenom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                prenomKeyTyped(evt);
            }
        });
        getContentPane().add(prenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 270, 206, -1));

        jButton2.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        jButton2.setText("Selectionne");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 137, 170, -1));

        jLabel3.setFont(new java.awt.Font("Andalus", 1, 20)); // NOI18N
        jLabel3.setText("Selectionner un client");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 138, 230, -1));

        di.setText("+212");
        getContentPane().add(di, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, -1, -1));

        sss.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Femme", "Homme" }));
        getContentPane().add(sss, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 435, 206, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/foto/gvff3.jpg"))); // NOI18N
        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -20, -1, -1));

        setSize(new java.awt.Dimension(722, 696));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        actualiser();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         client m=new client();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttActionPerformed
        // TODO add your handling code here:
                 if (cin.getText().equals("") || nom.getText().equals("") || prenom.getText().equals("") || teel.getText().equals("") || emmai.getText().equals("") || add.getText().equals("") ||sss.getSelectedItem().equals("")   ) {
 JOptionPane.showMessageDialog(this, "Remplir tous les champs");
 } 
                 else {
String[] colon = {"cin","nom","prenom","tel","email","adress","sex"};
 String[] inf = {cin.getText(), nom.getText(), prenom.getText(), teel.getText(), emmai.getText(),add.getText(), String.valueOf(sss.getSelectedItem())};
String idm = String.valueOf(idc.toString());
db.Updatedata("client", colon, inf, "cin='" + idm + "'");
System.out.println(db.Updatedata("client", colon, inf, "cin='" + idm + "'"));
 JOptionPane.showMessageDialog(this, "le client est modifié");
actualiser(); 
        }
       

    }//GEN-LAST:event_ttActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        deCm m=new deCm();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void teelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teelKeyTyped
        // TODO add your handling code here:
                 char car =evt.getKeyChar();
        if((car<'0' || car >'9') && teel.getText().contains("") &&(car!=(char)KeyEvent.VK_BACK_SPACE)){
        evt.consume();

    }else if((car<'0' || car >'9') &&(car!='.') 
            &&(car!=(char)KeyEvent.VK_BACK_SPACE)){
        evt.consume();
    }
        
             String mobileNo=teel.getText();
        if(mobileNo.matches("^[0-9]*$")&&mobileNo.length()>9)
        {
 JOptionPane.showMessageDialog(null,"Vérifiez votre numéro de téléphone","valider le numéro",JOptionPane.INFORMATION_MESSAGE);  
        }
    }//GEN-LAST:event_teelKeyTyped

    private void nomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomKeyTyped
        // TODO add your handling code here:
          char car = evt.getKeyChar();
        if ((car<'a'||car>'z')&& (car<'A'||car>'Z') && (car!=(char)KeyEvent.VK_BACK_SPACE) && (car!=(char)KeyEvent.VK_SPACE)){
            evt.consume();

        }
    }//GEN-LAST:event_nomKeyTyped

    private void prenomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prenomKeyTyped
        // TODO add your handling code here:
          char car = evt.getKeyChar();
        if ((car<'a'||car>'z')&& (car<'A'||car>'Z') && (car!=(char)KeyEvent.VK_BACK_SPACE) && (car!=(char)KeyEvent.VK_SPACE)){
            evt.consume();
//            JOptionPane.showMessageDialog(null,"seul le texte est autorisé","valider le texte",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_prenomKeyTyped

        public boolean adil(String email){
        Pattern pat = null;
        Matcher mat = null;
        pat = Pattern.compile("^[\\w\\-\\_\\+]+(\\.[\\w\\-\\_]+)*@([A-Za-z0-9-]+\\.)+[A-Za-z]{2,4}$");
        mat = pat.matcher(email);
        if(mat.find()){
            return true;
        }else{
            return false;
        }
    }
    private void emmaiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emmaiFocusLost
        // TODO add your handling code here:
            if(adil(emmai.getText())){
                
        }else{
                JOptionPane.showMessageDialog(null,"e-mail incorrect","valider le email",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_emmaiFocusLost

    private void cinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cinKeyTyped
        // TODO add your handling code here:
                         char car = evt.getKeyChar();
        if ((car<'a'||car>'z')&& (car<'A'||car>'Z') && (car!=(char)KeyEvent.VK_BACK_SPACE) && (car!=(char)KeyEvent.VK_SPACE)){
           
               
        if((car<'0' || car >'9') && cin.getText().contains("") &&(car!=(char)KeyEvent.VK_BACK_SPACE)){
        evt.consume();
        
    }else if((car<'0' || car >'9') &&(car!='.') 
            &&(car!=(char)KeyEvent.VK_BACK_SPACE)){
        evt.consume();
    }
        }
    }//GEN-LAST:event_cinKeyTyped

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
         di.setEditable(false);
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mdfclient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mdfclient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mdfclient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mdfclient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mdfclient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add;
    private javax.swing.JTextField cin;
    private javax.swing.JTextField di;
    private javax.swing.JTextField emmai;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField prenom;
    private javax.swing.JComboBox<String> sss;
    private javax.swing.JTextField teel;
    private javax.swing.JButton tt;
    // End of variables declaration//GEN-END:variables

   private void SetIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("rating.png")));
    }

   
}
