/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Database.dbcnx;
import Database.parameter;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
/**
 *
 * @author hp
 */
public class suppclient extends javax.swing.JFrame {

    /**
     * Creates new form suppclient
     */
    dbcnx db;
    
    String idc;
    String nomc;
    String pren;
    String te ;
    String ema;
    String ad;
    String s;
    public suppclient( String idcin , String nomc , String pren , String te , String ema , String ad , String s ) {
        this.idc=idcin;
        this.nomc=nomc;
        this.pren=pren;
        this.te=te;
        this.ema=ema;
        this.ad=ad;
        this.s=s;

        
        db=new dbcnx(new parameter().HOST_DB,new parameter().USERNAME_DB,new parameter().PASSWORD_DB,new parameter().IPHOST,new parameter().PORT);
        initComponents();
        cin.setText(idc);   
        nom.setText(nomc); 
        prenom.setText(pren);
        teel.setText(te);   
        emmai.setText(ema); 
        add.setText(ad);
        sss.setText(s);
        
        
    }
    public suppclient() {
        db=new dbcnx(new parameter().HOST_DB,new parameter().USERNAME_DB,new parameter().PASSWORD_DB,new parameter().IPHOST,new parameter().PORT);
        initComponents();
        setResizable(false);
        SetIcon();
    }
    
     public void actualiser(){
        cin.setText("");
        nom.setText("");
        prenom.setText("");
        emmai.setText("");
        add.setText("");
        sss.setText(""); 
        teel.setText("");
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        prenom = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        teel = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        emmai = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        add = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cin = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        sss = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 450));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(nom);
        nom.setBounds(296, 223, 206, 26);

        jLabel2.setFont(new java.awt.Font("Algerian", 1, 22)); // NOI18N
        jLabel2.setText("Supprimer Client");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(261, 43, 230, 30);

        jLabel4.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        jLabel4.setText("Cin");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(105, 180, 42, 27);

        jLabel5.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        jLabel5.setText("Nom");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(105, 223, 42, 27);
        getContentPane().add(prenom);
        prenom.setBounds(296, 268, 206, 26);

        jLabel6.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        jLabel6.setText("Tel");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(105, 304, 38, 27);
        getContentPane().add(teel);
        teel.setBounds(296, 313, 206, 26);

        jLabel7.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        jLabel7.setText("Email");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(105, 352, 64, 27);
        getContentPane().add(emmai);
        emmai.setBounds(296, 356, 206, 26);

        jLabel9.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        jLabel9.setText("sex");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(105, 440, 40, 27);
        getContentPane().add(add);
        add.setBounds(296, 395, 206, 26);

        jButton1.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/foto/refresh.png"))); // NOI18N
        jButton1.setText("Actualiser");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(393, 497, 200, 35);

        jLabel11.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        jLabel11.setText("Adress");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(105, 395, 80, 27);

        jButton2.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/foto/trash.png"))); // NOI18N
        jButton2.setText("Supprimer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(174, 498, 180, 35);

        jButton3.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/foto/close.png"))); // NOI18N
        jButton3.setText("Fermer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(298, 551, 160, 35);
        getContentPane().add(cin);
        cin.setBounds(296, 181, 206, 26);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/foto/icons8-delete-document-50.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(183, 30, 69, 65);
        getContentPane().add(sss);
        sss.setBounds(297, 440, 205, 26);

        jLabel10.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        jLabel10.setText("prenom");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(105, 261, 82, 27);

        jLabel3.setFont(new java.awt.Font("Andalus", 1, 20)); // NOI18N
        jLabel3.setText("Selectionner un client");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(78, 122, 220, 32);

        jButton4.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        jButton4.setText("Selectionne");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(303, 121, 180, 35);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/foto/gvff3.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-19, -10, 770, 670);

        setSize(new java.awt.Dimension(722, 696));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        actualiser();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         client m=new client();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                       if (cin.getText().equals("") || nom.getText().equals("") || prenom.getText().equals("") || teel.getText().equals("") || emmai.getText().equals("") || add.getText().equals("") || sss.getText().equals("")   ) {
 JOptionPane.showMessageDialog(this, "Remplir tous les champs");
 } else{
         String ids=String.valueOf(idc.toString());
        if(JOptionPane.showConfirmDialog(this,"etes-vous sur de vouloir supprimer","attention!",JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){
           System.out.println(db.DeleteData(" client "," cin = '"+ids+"'"));
        }else{return;}
        actualiser();
                       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        deCs m=new deCs();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
         cin.setEditable(false);
         nom.setEditable(false);
         prenom.setEditable(false);
         emmai.setEditable(false);
         teel.setEditable(false);
         add.setEditable(false); 
         sss.setEditable(false);
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(suppclient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(suppclient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(suppclient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(suppclient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new suppclient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add;
    private javax.swing.JTextField cin;
    private javax.swing.JTextField emmai;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField prenom;
    private javax.swing.JTextField sss;
    private javax.swing.JTextField teel;
    // End of variables declaration//GEN-END:variables
 private void SetIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("rating.png")));
    }
}
